export const mockDevices = [
  {
    _id: 'dev-001',
    deviceId: 'DEV-TH-101',
    name: 'Cold Storage Room A',
    type: 'Temperature',
    status: 'online',
    location: 'Warehouse Alpha - Zone 1',
    batteryLevel: 92,
    firmwareVersion: 'v2.1.0',
    lastSeen: 'Just now',
  },
  {
    _id: 'dev-002',
    deviceId: 'DEV-TH-102',
    name: 'Server Room HVAC Unit',
    type: 'Temperature',
    status: 'warning',
    location: 'HQ Data Center - Floor 3',
    batteryLevel: 68,
    firmwareVersion: 'v2.0.4',
    lastSeen: '5m ago',
  },
  {
    _id: 'dev-003',
    deviceId: 'DEV-VB-201',
    name: 'Main Turbine Motor 1',
    type: 'Vibration',
    status: 'online',
    location: 'Power Plant - Bay 2',
    batteryLevel: 98,
    firmwareVersion: 'v3.0.1',
    lastSeen: '1m ago',
  },
  {
    _id: 'dev-004',
    deviceId: 'DEV-PR-301',
    name: 'Hydraulic Line Pressure B',
    type: 'Pressure',
    status: 'online',
    location: 'Assembly Plant - Unit 5',
    batteryLevel: 85,
    firmwareVersion: 'v1.4.2',
    lastSeen: '30s ago',
  },
  {
    _id: 'dev-005',
    deviceId: 'DEV-MS-401',
    name: 'Greenhouse Ambient Pod',
    type: 'Multi-Sensor',
    status: 'offline',
    location: 'Agri-Tech Zone - Quad 9',
    batteryLevel: 14,
    firmwareVersion: 'v1.1.8',
    lastSeen: '3h ago',
  },
];

export const mockTelemetryChartData = [
  { time: '00:00', temperature: 21.2, humidity: 48, pressure: 1012, vibration: 0.12 },
  { time: '02:00', temperature: 20.8, humidity: 50, pressure: 1012, vibration: 0.14 },
  { time: '04:00', temperature: 20.1, humidity: 53, pressure: 1013, vibration: 0.11 },
  { time: '06:00', temperature: 21.5, humidity: 55, pressure: 1013, vibration: 0.18 },
  { time: '08:00', temperature: 23.4, humidity: 52, pressure: 1014, vibration: 0.28 },
  { time: '10:00', temperature: 26.2, humidity: 46, pressure: 1013, vibration: 0.35 },
  { time: '12:00', temperature: 28.5, humidity: 42, pressure: 1011, vibration: 0.39 },
  { time: '14:00', temperature: 31.8, humidity: 39, pressure: 1010, vibration: 0.44 },
  { time: '16:00', temperature: 33.2, humidity: 41, pressure: 1009, vibration: 0.49 },
  { time: '18:00', temperature: 29.4, humidity: 45, pressure: 1010, vibration: 0.32 },
  { time: '20:00', temperature: 26.1, humidity: 47, pressure: 1011, vibration: 0.22 },
  { time: '22:00', temperature: 23.9, humidity: 49, pressure: 1012, vibration: 0.15 },
  { time: 'Now',   temperature: 24.6, humidity: 50, pressure: 1012, vibration: 0.16 },
];

export const mockAlerts = [
  {
    _id: 'alt-001',
    deviceId: 'DEV-TH-102',
    title: 'HVAC Temperature Spike Exceeded Limit',
    message: 'Ambient rack temperature reached 33.8°C, exceeding 32.0°C critical threshold.',
    severity: 'critical',
    status: 'active',
    timestamp: '14m ago',
    valueDetected: '33.8°C',
  },
  {
    _id: 'alt-002',
    deviceId: 'DEV-VB-201',
    title: 'Turbine Motor 1 Vibration Surge',
    message: 'Harmonic vibration detected at 0.48 G (Warning limit: 0.45 G). Inspect bearing.',
    severity: 'warning',
    status: 'active',
    timestamp: '1h ago',
    valueDetected: '0.48 G',
  },
  {
    _id: 'alt-003',
    deviceId: 'DEV-MS-401',
    title: 'Greenhouse Pod Battery Depleted',
    message: 'Device reported 14% battery capacity and went offline. Scheduled for solar pack swap.',
    severity: 'warning',
    status: 'acknowledged',
    timestamp: '3h ago',
    valueDetected: '14%',
  },
  {
    _id: 'alt-004',
    deviceId: 'DEV-PR-301',
    title: 'Pressure Regulator Calibration Complete',
    message: 'Hydraulic Line 5 returned to nominal baseline 180 bar.',
    severity: 'info',
    status: 'resolved',
    timestamp: '6h ago',
    valueDetected: '180 bar',
  },
];

export const mockRules = [
  {
    _id: 'rule-001',
    name: 'Overheat Detection & Shutdown',
    description: 'Triggers critical alert when server room temperature exceeds 32°C for 2 consecutive cycles.',
    enabled: true,
    targetDeviceId: 'DEV-TH-102',
    executionCount: 142,
    lastTriggered: '15m ago',
  },
  {
    _id: 'rule-002',
    name: 'Turbine Vibration Anomaly',
    description: 'Monitors turbine vibration amplitude and notifies maintenance if vibration > 0.45 G.',
    enabled: true,
    targetDeviceId: 'DEV-VB-201',
    executionCount: 88,
    lastTriggered: '1h ago',
  },
  {
    _id: 'rule-003',
    name: 'Low Battery Auto-Report',
    description: 'Flags any remote sensor dropping below 20% remaining battery.',
    enabled: false,
    targetDeviceId: 'all',
    executionCount: 29,
    lastTriggered: 'Never',
  },
];
